name: state_machine_bloc
description: state_machine_bloc is an extension to the bloc state management library which provide a convenient way to create finite state machines based blocs.
version: 0.0.1-dev.4
homepage: https://github.com/Pierre2tm/state_machine_bloc
repository: https://github.com/Pierre2tm/state_machine_bloc

environment:
  sdk: ">=2.16.1 <3.0.0"

dev_dependencies:
  lints: ^1.0.0
  test: ^1.20.2

dependencies: 
  bloc: ^8.0.2
  bloc_concurrency: ^0.2.0
  meta: ^1.7.0
