name: flutter_timer_state_machine
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  state_machine_bloc:
    path: ../../packages/state_machine_bloc/

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.0
  mocktail: ^0.2.0

flutter:
  uses-material-design: true
